# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b46f028884f54a5dc9e0dbceca9f2b5d"
name = "next app"
application_url = "https://que-lexus-cups-bigger.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-10a506ed.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://que-lexus-cups-bigger.trycloudflare.com/auth/callback",
  "https://que-lexus-cups-bigger.trycloudflare.com/auth/shopify/callback",
  "https://que-lexus-cups-bigger.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
